name: CI Pipeline
 
on:
  push:
    branches: [main]
 
jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: SSH to Server

        uses: appleboy/ssh-action@v1.0.3

        with:

          host: ${{ secrets.HOST }}

          username: ${{ vars.USERNAME }}

          key: ${{ secrets.KEY }}

          script: |

            docker stop resume || echo ""

            docker rm resume || echo ""

            docker run -d --name resume -p 8080:5001 ${{ secrets.REGISTRY_USERNAME }}/my-image-name:${{ github.run_number }}

 